const menu = [
    {
        id: 1,
        number: '91',
        name: 'Steven Stamkos',
        category: 'Center',
        born: 'February 7, 1990',
        birthplace: 'Markham, ON, CAN',
        shoots: 'Right',
        img: './images/item-1.jpeg',
        desc: `Stamkos was limited to one game and 2:47 of ice time during the Tampa Bay Lightning's run to their second Stanley Cup championship in 2020. He made the most of his brief stint, scoring a first-period goal in Game 3 of the Cup Final against the Dallas Stars. Stamkos made his only other playoff appearance after Tampa Bay's 2-0 victory in Game 6, when as captain of the Lightning he accepted the Cup from NHL Commissioner Gary Bettman. The following season, Stamkos helped Tampa Bay repeat as Stanley Cup champions with a five-game victory against the Montreal Canadiens in the best-of-7 Final.
        Though his cameo in Game 3 was the only action he saw after Feb. 25 -- he had surgery to repair a core muscle injury, then sustained a lower-body injury before summer training camp opened in July -- Stamkos has emerged as one of the top goal-scorers of his generation since the Lightning selected him at No. 1 in the 2008 NHL Draft.`,
    },
    {
        id: 2,
        number: '88',
        name: 'Andrei Vasilevskiy',
        category: 'Goalie',
        born: 'July 25, 1994',
        birthplace: 'Tyumen, RUS ',
        shoots: 'Left',
        img: './images/item-2.jpeg',
        desc: `Vasilevskiy's second trip to the Stanley Cup Final ended better than the first one.
        He earned a win in relief as a 21-year-old for the Tampa Bay Lightning during the 2015 Final, but the Chicago Blackhawks won the series in six games. Five years later, Vasilevskiy played every minute during the Lightning's 25 postseason games and made 22 saves in a 2-0 victory against the Dallas Stars in Game 6, wrapping up Tampa Bay's second championship since entering the NHL in 1992.`,
    },
    {
        id: 3,
        number: '12',
        name: 'Alex Barré-Boulet',
        category: 'Center',
        born: 'May 21, 1997',
        birthplace: 'Montmagny, QC, CAN',
        shoots: 'Left',
        img: './images/item-3.jpeg',
        desc: `No information`,
    },
    {
        id: 4,
        number: '98',
        name: 'Mikhail Sergachev',
        category: 'Defensemen',
        born: 'June 25, 1998 ',
        birthplace: 'Nizhnekamsk, RUS',
        shoots: 'Left',
        img: './images/item-4.jpeg',
        desc: `Sergachev was selected in the first round (No. 9) of the 2016 NHL Draft by the Montreal Canadiens after he had 57 points (17 goals, 40 assists) for Windsor of the Ontario Hockey League. That season, his first in North America after playing in Russia, he finished third among defenseman in scoring and won the Max Kaminsky Trophy as the top defenseman.
        On July 1, 2016, Sergachev signed a three-year, entry-level contract with the Canadiens.`,
    },
    {
        id: 5,
        number: '44',
        name: 'Jan Rutta',
        category: 'Defensemen',
        born: 'July 29, 1990',
        birthplace: 'Pisek, CZE',
        shoots: 'Right',
        img: './images/item-5.jpeg',
        desc: `Rutta, a native of the Czech Republic, spent seven seasons playing in his home country before signing a one-year contract with the Chicago Blackhawks on June 7, 2017.
        The 27-year-old defenseman made the team out of training camp and scored his first NHL goal against the Toronto Maple Leafs on Oct. 9, 2017, beating goalie Frederik Andersen. The Blackhawks were impressed enough with his performance to sign him to a one-year contract on March 8, 2018.`,
    },
    {
        id: 6,
        number: '93',
        name: 'Anthony Richard',
        category: 'Center',
        born: 'December 20, 1996 ',
        birthplace: 'Trois-Rivières, QC, CAN ',
        shoots: 'Left',
        img: './images/item-6.jpeg',
        desc: `Traded to Tampa Bay by Nashville for Jimmy Huntington, February 1, 2022.`,
    },
    {
        id: 7,
        number: '86',
        name: 'Nikita Kucherov',
        category: 'Left Wing',
        born: 'June 17, 1993 ',
        birthplace: 'Maykop, RUS',
        shoots: 'Left',
        img: './images/item-7.jpeg',
        desc: `Kucherov was a second-round pick (No. 58) by the Tampa Bay Lightning in the 2011 NHL Draft but has played like a first-round talent. He won the Art Ross Trophy as the NHL's top scorer in 2018-19 with 128 points (41 goals, 87 assists), the most in a single season by a player born in Russia, and was voted winner of the Hart and Ted Lindsay trophies.
        Though Kucherov got off to a slow start in 2019-20, he ended the season with 85 points (33 goals, 52 assists) in 68 games, then led all scorers during Tampa Bay's run to the Stanley Cup with 34 points (seven goals, 27 assists) in 25 postseason games.`,
    },
    {
        id: 8,
        number: '21',
        name: 'Brayden Point',
        category: 'Center',
        born: 'March 13, 1996 ',
        birthplace: 'Calgary, AB, CAN ',
        shoots: 'Right',
        img: './images/item-8.jpeg',
        desc: `Point was a big reason the Tampa Bay Lightning won the second Stanley Cup championship in their history in 2020, defeating the Dallas Stars in a six-game Final. He led all players in the postseason with 14 goals; the last one, a power-play goal at 12:23 of the first period in Game 6, turned out to be the Cup-winner.
        The Lightning struck gold when they selected Point in the third round (No. 79) of the 2014 NHL Draft after he scored 91 points (36 goals, 55 assists) in 72 games for Moose Jaw of the Western Hockey League.`,
    },
    {
        id: 9,
        number: '10',
        name: 'Corey Perry',
        category: 'Right Wing',
        born: 'May 16, 1985 ',
        birthplace: 'Peterborough, ON, CAN',
        shoots: 'Right',
        img: './images/item-9.jpeg',
        desc: `Perry combines a 6-foot-3 frame with a long reach and powerful skating stride to get past defenders. But the Peterborough, Ontario, native is also one of the NHL's biggest agitators; he has gotten under the skin of rivals by doing things such as spraying water in opponents' gloves and grabbing their sticks.
        However, Perry, selected by the Mighty Ducks of Anaheim in the first round (No. 28) of the 2003 NHL Draft, also became one of the best goal-scorers of his generation. He became the third player from his draft class to reach 300 goals when he scored against the Edmonton Oilers on Nov. 11, 2015. Perry then scored No. 301 two nights later to move past Paul Kariya into second place in Anaheim history, behind Teemu Selanne.`,
    },
    {
        id: 10,
        number: '20',
        name: 'Nicholas Paul',
        category: 'Left Wing',
        born: 'March 20, 1995',
        birthplace: 'Mississauga, ON, CAN',
        shoots: 'Left',
        img: './images/item-10.jpeg',
        desc: `The hard-working Paul has emerged as one of the Senators' top defensive forwards.
        He was drafted by the Dallas Stars in the fourth round (No. 101) in the 2013 NHL Draft. His rights were traded to the Senators on July 1, 2014.`,
    },
    {
        id: 11,
        number: '18',
        name: 'Ondrej Palat',
        category: 'Left Wing',
        born: 'March 28, 1991 ',
        birthplace: 'Frydek-Mistek, CZE',
        shoots: 'Left',
        img: './images/item-11.jpeg',
        desc: `Palat, a native of the Czech Republic, was one of the keys to the Tampa Bay Lightning's run to the Stanley Cup in 2020. After not scoring a goal during Tampa Bay's first nine postseason games, Palat scored 11 in the final 16 -- including three during the Lightning's six-game victory against the Dallas Stars in the Stanley Cup Final. He was also second to teammate Nikita Kucherov in the playoffs with a plus-15 rating.
        The Lightning selected Palat in the seventh round (No. 208) of the 2011 NHL Draft but were not sure where the forward, who had gone undrafted the previous year, would fit into the organization. At the draft table there was some question about whether Tampa Bay should pick Palat or invite him to training camp.`,
    },
    {
        id: 12,
        number: '16',
        name: 'Riley Nash',
        category: 'Center',
        born: 'May 9, 1989 ',
        birthplace: 'Consort, AB, CAN',
        shoots: 'Right',
        img: './images/item-12.jpeg',
        desc: `Selected by the Edmonton Oilers in the first round (No. 21) of the 2007 NHL Draft, Nash played alongside his brother, Brenden, at Cornell University and was named ECAC Rookie of the Year with 12 goals and 20 assists.
        But following his junior year, the Oilers traded Nash's rights to the Carolina Hurricanes on June 25, 2010 for a second-round pick at that year's Draft. Nash signed a three-year, entry level contract with the Hurricanes on July 19, 2010.`,
    },
    {
        id: 13,
        number: '27',
        name: 'Ryan McDonagh',
        category: 'Defensemen',
        born: 'June 13, 1989',
        birthplace: 'St. Paul, MN, USA ',
        shoots: 'Left',
        img: './images/item-13.jpeg',
        desc: `McDonagh made a big impact with his all-around game long before he reached the NHL, and he's continued to make an impact with the New York Rangers and Tampa Bay Lightning. He helped the Rangers make the Stanley Cup Final in 2014 and was a top-four defenseman for the Lightning when they won the Cup in 2020.
        The nephew of former NFL and University of Miami quarterback Steve Walsh started to stand out in high school with Cretin-Derham Hall in St. Paul, Minnesota. As a junior in 2006, he helped lead Cretin-Derham to its first state championship with 12 goals and 45 points. As a senior in 2007, McDonagh was named Mr. Hockey for the state of Minnesota after finishing with 14 goals and 40 points in 26 games.`,
    },
    {
        id: 14,
        number: '14',
        name: 'Pat Maroon',
        category: 'Left Wing',
        born: 'April 23, 1988',
        birthplace: 'St. Louis, MO, USA',
        shoots: 'Left',
        img: './images/item-14.jpeg',
        desc: `Not many players win the Stanley Cup with different teams in consecutive years, but Maroon is one of them. After helping his hometown St. Louis Blues win their first championship in 2019, he signed with the Tampa Bay Lightning on Aug. 24, 2019, and was a valuable role player during their run to the Cup in 2020.
        Maroon came home when he signed with the Blues on July 10, 2018, 11 years after the Philadelphia Flyers selected him in the sixth round (No. 161) in the 2007 NHL Draft.`,
    },
    {
        id: 15,
        number: '17',
        name: 'Alex Killorn',
        category: 'Left Wing',
        born: 'September 14, 1989',
        birthplace: 'Halifax, NS, CAN',
        shoots: 'Left',
        img: './images/item-15.jpeg',
        desc: `Killorn capped the best season of his NHL career in 2019-20 by helping the Tampa Bay Lightning win the Stanley Cup for the first time since 2004. He scored five goals and 10 points in 25 postseason games, including one goal and one assist in Game 4 of the Stanley Cup Final against the Dallas Stars.
        Born in Halifax, Nova Scotia, and raised outside of Montreal, Killorn was selected in the third round (No. 77) by Tampa Bay in the 2007 NHL Draft, but had committed to attend Harvard University starting in the fall of 2009. `,
    },
    {
        id: 16,
        number: '77',
        name: 'Victor Hedman',
        category: 'Defensemen',
        born: 'December 18, 1990',
        birthplace: 'Ornskoldsvik, SWE',
        shoots: 'Left',
        img: './images/item-16.jpeg',
        desc: `The Tampa Bay Lightning expected Hedman to grow into an elite defenseman when they selected him with the No. 2 pick in the 2009 NHL Draft. Those expectations have been amply rewarded.
        Hedman was voted winner of the Norris Trophy as the NHL's top defenseman in 2018. Two years later, he was voted winner of the Conn Smythe Trophy as the most valuable player in the Stanley Cup Playoffs after helping the Lightning win their second championship since entering the NHL in 1992. Hedman scored 10 goals, the most by a defenseman since Brian Leetch of the New York Rangers scored 11 in 1994. His average ice time of 26:20 was the most of any player whose team got as far as the second round of the playoffs.`,
    },
    {
        id: 17,
        number: '82',
        name: 'Gabriel Fortier',
        category: 'Left Wing',
        born: 'February 6, 2000',
        birthplace: 'Lachine, QC, CAN',
        shoots: 'Left',
        img: './images/item-17.jpeg',
        desc: `No information`,
    },
    {
        id: 18,
        number: '52',
        name: 'Cal Foote',
        category: 'Defensemen',
        born: 'December 13, 1998',
        birthplace: 'Denver, CO, USA',
        shoots: 'Right',
        img: './images/item-18.jpeg',
        desc: `No information`,
    },
    {
        id: 19,
        number: '1',
        name: 'Brian Elliott',
        category: 'Goalie',
        born: 'April 9, 1985',
        birthplace: 'Newmarket, ON, CAN',
        shoots: 'Left',
        img: './images/item-19.jpeg',
        desc: `Elliott's goaltending journey is one of perseverance and unwavering self-belief.
        Elliott was playing for Ajax of the Ontario Provincial Junior A League when he was selected by the Ottawa Senators in the ninth round (No. 291), the next-to-last player picked in the 2003 NHL Draft.`,
    },
    {
        id: 20,
        number: '79',
        name: 'Ross Colton',
        category: 'Center',
        born: 'September 11, 1996',
        birthplace: 'Robbinsville, NJ, USA',
        shoots: 'Left',
        img: './images/item-20.jpeg',
        desc: `It didn't take long for Ross Colton to fit in with the Tampa Bay Lightning.
        The forward was chosen in the fourth round (No. 118) of the 2016 NHL Draft and scored a goal on his first and only shot of his NHL debut, a 3-0 win against the Carolina Hurricanes on Feb. 24, 2021. He joined Nikita Kucherov as the only players in Lightning history to score a game-winning goal in their first NHL game.`,
    },
    {
        id: 21,
        number: '71',
        name: 'Anthony Cirelli',
        category: 'Center',
        born: 'July 15, 1997',
        birthplace: 'Etobicoke, ON, CAN',
        shoots: 'Left',
        img: './images/item-21.jpeg',
        desc: `Cirelli played a key role for the Tampa Bay Lightning in their run to the Stanley Cup championship in 2020. His overtime goal in Game 6 of the Eastern Conference Final against the New York Islanders put the Lightning into the Stanley Cup Final for the first time since 2015, and he contributed three assists in six games against the Dallas Stars in the Cup Final to help Tampa Bay win its first championship since 2004.
        The Lightning selected Cirelli in the third round (No. 72) of the 2015 NHL Draft after he had 36 points (13 goals, 23 assists) for Oshawa of the Ontario Hockey League. He scored twice including in overtime in the 2015 Memorial Cup final against Kelowna of the Western Hockey League.`,
    },
    {
        id: 22,
        number: '81',
        name: 'Erik Cernak',
        category: 'Defensemen',
        born: 'May 28, 1997',
        birthplace: 'Kosice, SVK',
        shoots: 'Right',
        img: './images/item-22.jpeg',
        desc: `Cernak, a defenseman from Kosice, Slovakia, attracted the attention of NHL scouts in his first full pro season with his hometown team in the country's top pro league. The Los Angeles Kings selected him in the second round (No. 43) of the 2015 NHL Draft.
        After being drafted, Cernak opted to come to North America, playing two seasons with Erie of the Ontario Hockey League. But before his second season in Erie ended, he was traded to the Tampa Bay Lightning on Feb. 26, 2017.`,
    },
    {
        id: 23,
        number: '24',
        name: 'Zach Bogosian',
        category: 'Defensemen',
        born: 'July 15, 1990 ',
        birthplace: 'Massena, NY, USA',
        shoots: 'Right',
        img: './images/item-23.jpeg',
        desc: `Bogosian's NHL career took a 180-degree turn in February 2020. The Buffalo Sabres, on their way to missing the Stanley Cup Playoffs for the ninth consecutive season, placed the 12-year defenseman on waivers Feb. 21, with the intention of terminating his contract. Two days later, he signed with the Tampa Bay Lightning, who went on to win the Stanley Cup. Bogosian, who had never played a postseason game since entering the NHL in 2008, averaged 17:40 of ice time in 20 playoff games and finished with four assists.
        The Atlanta Thrashers selected Bogosian with the No. 3 pick in the 2008 NHL Draft, and he made the club out of training camp that fall. When he made his NHL debut against the Washington Capitals on Oct. 10, 2008, he became the youngest player in Thrashers history at 18 years and 87 days.`,
    },
    {
        id: 24,
        number: '41',
        name: 'Pierre-Edouard Bellemare',
        category: 'Left Wing',
        born: 'March 6, 1985',
        birthplace: 'Le Blanc-Mesnil, FRA',
        shoots: 'Left',
        img: './images/item-24.jpeg',
        desc: `Bellemare became the ninth player born in France to reach the NHL when he joined the Philadelphia Flyers for the start of the 2014-15 season at age 29. But were it not for the eight years he spent playing in Sweden, the native of the Paris suburb of Le Blanc-Mesnil said he might never have worn an NHL sweater.
        Bellemare played five seasons in the Swedish Elite League (now the Swedish Hockey League) for Skelleftea AIK. He developed into an NHL-worthy player, scoring 64 goals and 125 points in 238 games and winning the SEL title in 2013 and 2014. Bellemare credited his coaches at Skelleftea for helping to hone his face-off skills and improving his work in the defensive zone.`,
    },
  ];
  export default menu;
  